# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CICD BE

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      job_name:
        description: 'Run Job BE'
        required: true
        default: 'build_be'
      # job_name:
      #   description: 'Run Job FE'
      #   required: true
      #   default: 'build_fe'
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  build_be:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BE
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      # - name: Test
      #   run: mvn test -Dtest=com.chien.bookWorld.*Tests

      # - name: Publish Test Report
      #   uses: mikepenz/action-junit-report@v4
      #   if: success() || failure() # always run even if the previous step fails
      #   with:
      #     report_paths: '**/TEST-*.xml'    

      - name: Heroku Install
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku plugins:install java

      - name: Heroku Deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run:
          heroku deploy:jar target/*.jar --app book-world

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive1
      # - name: Update dependency graph1 
      #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
  # build_fe:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./FE
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Npm Install Packages
  #       run: npm i

  #     - name: Build Package
  #       env:
  #         CI: false
  #       run: npm run build

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive1
      # - name: Update dependency graph
      #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
